id: 25b045e8ef174099b3bd25fa654c0408
initial_creation_type: ocr
source_metadata:
  volumes:
    7d90cbba188f4947885203fb376a2d0c:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
